name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COLUMNS: "120"
      NO_COLOR: "1"
      TERM: dumb
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: libjpeg
        run: sudo apt-get update && sudo apt-get install -y libjpeg-dev
      - name: Install
        run: pip install -e ".[dev,jpeg]"
      - name: Pytest
        run: pytest -q
